### ISSUE TITLE
Delete last node of doubly linked list

### ISSUE THREAD

**Issue by RajaParivesh** [RajaParivesh/JavaPracticeCode#1]
# Getting this error message:
**Exception in thread "main" java.lang.NullPointerException	at collections.linkedList.doublyLinkedList.DoublyLinkedList.deleteLast(DoublyLinkedList.java:75)
at collections.Main.main(Main.java:46)**

**Comment by RajaParivesh** [comment]
Check Delete the last node of doubly linked list code. Solved
